polls/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('question/<int:pk>/detail', views.DetailView.as_view(), name='detalhes'),
    path('question/<int:question_id>/results', views.results, name='resultado'),
    path('question/<int:question_id>/vote', views.vote, name='votacao'),
    path('question/<int:category_id>/categories', views.category, name='categorias'),
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

polls/main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1) <= self.pub_date <= now

    def list_categories(self):
        return self.category_set.all()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Category(models.Model):
    questions = models.ManyToManyField(Question)
    category_text = models.CharField(max_length=100)
    category_description = models.CharField(max_length=300)
    date_created = models.DateTimeField('Data de criação')
    def __str__(self):
        return self.category_text

    def list_polls(self):
        questions = self.questions.all()
        return questions.order_by('question_text')

polls/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice, Category


def index(request):
    # sinal de menos (-) para falar mostrar decrescente
    latest_question = Question.objects.filter(
        pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
    # template = loader.get_template('main/index.html')
    context = { 'latest_question': latest_question, }

    return render(request, 'main/index.html', context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'main/detail.html', {'question': question, 'error_message': "Você não selecionou uma opção"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('main:resultado', args=(question.id,)))

def category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return render(request, 'main/category.html', {'category': category})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'main/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte = timezone.now())

polls/main/templates/main/category.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
        <title>Categorias</title>
    </head>
    <body>
        {% if category %}
        <div class="header">
            <h2>Lista de Enquetes da categoria {{ category.category_text }}</h2>
        </div>
            <ul>
                {% for question in category.list_polls %}
                <li><a href="{% url 'main:detalhes' question.id%}">
                    {{ question.question_text }}
                </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>Nenhuma questão disponível.</h3>
        {% endif %}
        <hr/>
        <a class="a_button" href="{% url 'main:index' %}">Retornar à pagína principal </a>
    </body>
</html>

polls/main/templates/main/detail.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
        <title>Detalhes</title>
    </head>
    <body>
        <div class="header">
        <h2>Detalhes da Enquete {{ question.id }}</h2>
        </div>
        <div class="infos">
        <u>Categoria</u>:
        {% for category in question.list_categories %}
            <a href="{% url 'main:categorias' category.id %}">{{ category }}</a>
        {% endfor %}
        <br/>
        <u>Data de Publicação</u>: {{ question.pub_date }}<br/>
        </div>
        <hr/>
        <div><h3>{{ question.question_text }}</h3></div>
        {% if error_message %}
            <hr/>
            <strong>{{ error_message }}</strong>
            <hr/>
        {% endif %}
        <form action="{% url 'main:votacao' question.id %}" method="post">
            {% csrf_token %}
            <div class="radiusContent">{% for choice in question.choice_set.all %}
                    <div class="radiusItem">
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
                    </div>
            {% endfor %}</div>
            <input class="button" type="submit" value="Registre o seu voto"/>
        </form>
    </body>
</html>

polls/main/templates/main/index.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
        <title>Polls Aplication</title>
    </head>
    <body>
        {% if latest_question %}
        <div class="header">
            <h2>Lista de últimas Enquetes</h2>
        </div>
            <ul>
                {% for question in latest_question %}
                <li><a href="{% url 'main:detalhes' question.id%}">
                    {{ question.question_text }}
                </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>Nenhuma questão disponível.</h3>
        {% endif %}
    </body>
</html>

polls/main/templates/main/results.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
        <title>App Enquete</title>
    </head>
    <body>
        <div class="header">
        <h2>Resultado Parcial da Enquete {{ question.id }}</h2>
        </div>
        <div class="infos">
        <u>Categoria</u>:
        {% for category in question.list_categories %}
            <a href="{% url 'main:categorias' category.id %}">{{ category }}</a>
        {% endfor %}
        <br/>
        <u>Data de Publicação</u>: {{ question.pub_date }}<br/>
        </div>
        <hr/>
        <div><h3>{{ question.question_text }}</h3></div>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} = {{ choice.votes }} voto{{ choice.votes | pluralize }}</li>
            {% endfor %}
        </ul>
        <hr/>
        <a class="a_button" href="{% url 'main:detalhes' question.id %}">Deseja votar novamente?</a>
        <a class="a_button" href="{% url 'main:index' %}">Retornar à pagína principal </a>
    </body>
</html>